[package]
name = "day09"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
itertools = {workspace = true }
